#!/usr/bin/env python3
"""Make the web fonts in assets/fonts/ from the original font files (run by hand, rarely).

    pip install fonttools brotli
    python3 scripts/build-fonts.py <folder with the downloaded fonts>

The folder holds the font repositories as downloaded:
    open-huninn-font/font/jf-openhuninn-2.1.ttf          github.com/justfont/open-huninn-font
    genyo-font/otf/TW/GenKiMin2TW-R.otf, -B.otf          github.com/ButTaiwan/genyo-font
    Minipax/fonts/webfonts/Minipax-Regular.woff2, -Bold   github.com/ronotypo/Minipax
    cirrus/CirrusCumulus.otf                              gitlab.com/Clarasambot/cirruscumulus

Latin fonts are copied unchanged. The Chinese fonts are far too large for the web (5 to 13 MB),
so they are cut into chunks with a unicode-range each: the browser downloads only the chunks
holding characters on the page. The first chunk holds every Chinese character the site uses;
the rest cover the Big5 character set (for blog posts and chat answers). Subsetting makes them
modified versions under the SIL OFL, so they get new names: "jf open huninn" is a Reserved Font
Name. Writes assets/fonts/fonts.css and copies the licences to assets/fonts/LICENSES/."""
import glob, os, re, shutil, sys
from fontTools.ttLib import TTFont
from fontTools import subset

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "fonts")
SRC = sys.argv[1] if len(sys.argv) > 1 else "."
CHUNK = 1000  # characters per chunk after the first

# (CSS family, weight, source file, new internal name, licence file)
CJK = [
    ("LTC Round", 400, "open-huninn-font/font/jf-openhuninn-2.1.ttf", "LTC Round", "open-huninn-font/LICENSE"),
    ("GenKi Min2 TW", 400, "genyo-font/otf/TW/GenKiMin2TW-R.otf", "GenKi Min2 TW Web", "genyo-font/SIL_Open_Font_License_1.1.txt"),
    ("GenKi Min2 TW", 700, "genyo-font/otf/TW/GenKiMin2TW-B.otf", "GenKi Min2 TW Web", "genyo-font/SIL_Open_Font_License_1.1.txt"),
]
LATIN = [  # (CSS family, weight, source, file name in assets/fonts, format, licence)
    ("Minipax", 400, "Minipax/fonts/webfonts/Minipax-Regular.woff2", "Minipax-Regular.woff2", "woff2", "Minipax/LICENSE.txt"),
    ("Minipax", 700, "Minipax/fonts/webfonts/Minipax-Bold.woff2", "Minipax-Bold.woff2", "woff2", "Minipax/LICENSE.txt"),
    ("CirrusCumulus", 400, "cirrus/CirrusCumulus.otf", "CirrusCumulus.otf", "opentype", "cirrus/LICENSE"),
]


def is_cjk(c):
    o = ord(c)
    return (0x2E80 <= o <= 0x9FFF or 0xF900 <= o <= 0xFAFF or 0xFE30 <= o <= 0xFE4F
            or 0xFF00 <= o <= 0xFFEF or 0x20000 <= o <= 0x3FFFF)


def site_chars():
    chars = set()
    pats = ["**/*.html", "posts/*.md", "data/*.json", "data/*.md"]
    for pat in pats:
        for p in glob.glob(os.path.join(ROOT, pat), recursive=True):
            if "/node_modules/" in p or "/assets/fonts/" in p:
                continue
            with open(p, encoding="utf-8", errors="ignore") as f:
                chars.update(c for c in f.read() if is_cjk(c))
    return chars


def big5_chars():
    chars = set()
    for hi in range(0x81, 0xFF):
        for lo in list(range(0x40, 0x7F)) + list(range(0xA1, 0xFF)):
            try:
                c = bytes([hi, lo]).decode("big5")
            except UnicodeDecodeError:
                continue
            if len(c) == 1 and is_cjk(c):
                chars.add(c)
    return chars


def ranges(cps):
    cps, out, i = sorted(cps), [], 0
    while i < len(cps):
        j = i
        while j + 1 < len(cps) and cps[j + 1] == cps[j] + 1:
            j += 1
        out.append("U+%X" % cps[i] if i == j else "U+%X-%X" % (cps[i], cps[j]))
        i = j + 1
    return ", ".join(out)


def rename(font, family):
    name = font["name"]
    style = "Bold" if font["OS/2"].usWeightClass >= 600 else "Regular"
    for rec in list(name.names):
        if rec.nameID in (1, 3, 4, 6, 16, 17, 21, 22):
            name.removeNames(nameID=rec.nameID)
    full = "%s %s" % (family, style)
    ps = re.sub(r"[^A-Za-z0-9-]", "", family) + "-" + style
    for nid, val in ((1, family), (2, style), (3, ps + ";web"), (4, full), (6, ps)):
        name.setName(val, nid, 3, 1, 0x409)
        name.setName(val, nid, 1, 0, 0)


def main():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(os.path.join(OUT, "LICENSES"))
    css = ["/* Generated by scripts/build-fonts.py. Fonts and licences: assets/fonts/LICENSES/ */"]

    for fam, wt, src, fname, fmt, lic in LATIN:
        shutil.copy(os.path.join(SRC, src), os.path.join(OUT, fname))
        css.append("@font-face { font-family: \"%s\"; font-weight: %d; font-style: normal; font-display: swap; "
                   "src: url(\"%s\") format(\"%s\"); }" % (fam, wt, fname, fmt))

    used = site_chars()
    pool = big5_chars() | used
    for fam, wt, src, newname, lic in CJK:
        base = TTFont(os.path.join(SRC, src), lazy=True)
        have = set(base.getBestCmap())
        base.close()
        first = sorted(ord(c) for c in used if ord(c) in have)
        rest = sorted(ord(c) for c in pool - used if ord(c) in have)
        chunks = [first] + [rest[i:i + CHUNK] for i in range(0, len(rest), CHUNK)]
        slug = re.sub(r"[^a-z0-9]+", "-", newname.lower()).strip("-") + "-%d" % wt
        for n, cps in enumerate(chunks):
            opts = subset.Options()
            opts.flavor = "woff2"
            opts.layout_features = ["*"]
            opts.name_IDs = ["*"]
            opts.name_languages = ["*"]
            opts.notdef_outline = True
            opts.hinting = False
            f = subset.load_font(os.path.join(SRC, src), opts)
            s = subset.Subsetter(opts)
            s.populate(unicodes=cps)
            s.subset(f)
            rename(f, newname)
            fn = "%s-%02d.woff2" % (slug, n)
            subset.save_font(f, os.path.join(OUT, fn), opts)
            # Later chunks cover contiguous code-point spans, so their unicode-range is short.
            # The first chunk (the site's own characters) is scattered and is declared last:
            # where ranges overlap, the browser tries the last declared face first, so the
            # site's characters never pull in the later chunks.
            rng = ranges(cps) if n == 0 else "U+%X-%X" % (cps[0], cps[-1])
            rule = ("@font-face { font-family: \"%s\"; font-weight: %d; font-style: normal; font-display: swap; "
                    "src: url(\"%s\") format(\"woff2\"); unicode-range: %s; }" % (fam, wt, fn, rng))
            if n == 0:
                first_rule = rule
            else:
                css.append(rule)
            print(fn, len(cps), os.path.getsize(os.path.join(OUT, fn)) // 1024, "KB")
        css.append(first_rule)

    lic_files = {"open-huninn-font/LICENSE": "jf-open-huninn-OFL.txt",
                 "genyo-font/SIL_Open_Font_License_1.1.txt": "GenYo-GenKi-OFL.txt",
                 "Minipax/LICENSE.txt": "Minipax-OFL.txt",
                 "cirrus/LICENSE": "CirrusCumulus-OFL.txt"}
    for src, dst in lic_files.items():
        shutil.copy(os.path.join(SRC, src), os.path.join(OUT, "LICENSES", dst))
    with open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(css) + "\n")
    total = sum(os.path.getsize(p) for p in glob.glob(os.path.join(OUT, "*")) if os.path.isfile(p))
    print("first chunk: %d characters used on the site; total %.1f MB" % (len(used), total / 1e6))


if __name__ == "__main__":
    main()
