#!/usr/bin/env python3
"""Bundle the LLM wiki (wiki/index.md + wiki/pages/**) into worker/src/knowledge.js,
the knowledge base the homepage chat answers from.

The output is deterministic (sorted paths, no timestamps) so the Claude prompt cache
keeps hitting until the wiki itself changes. Wrangler runs this before every deploy."""
import glob, json, os, runpy

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(ROOT, "wiki")
OUT = os.path.join(ROOT, "worker", "src", "knowledge.js")

# The site map is generated from data/site.json, so it never lags behind the website.
runpy.run_path(os.path.join(ROOT, "scripts", "wiki-sitemap.py"))

files = ["index.md"] + sorted(os.path.relpath(p, WIKI) for p in glob.glob(os.path.join(WIKI, "pages", "**", "*.md"), recursive=True))
parts = []
for rel in files:
    with open(os.path.join(WIKI, rel), encoding="utf-8") as f:
        parts.append('<page path="%s">\n%s\n</page>' % (rel, f.read().strip()))
text = "\n\n".join(parts)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/build-knowledge.py from wiki/. Do not edit.\n")
    f.write("export default %s;\n" % json.dumps(text, ensure_ascii=False))
print("knowledge.js: %d pages, %d characters" % (len(files), len(text)))
